### ISSUE TITLE
Support for doctrine/dbal v4

### ISSUE THREAD

**Issue by eatame** [darsyn/ip-doctrine#1]
Hi, doctrine/dbal has sable version 4. It looks like this library is compatible with that version, but composer.json is limited to "^2.3 || ^3".

**Comment by zanbaldwin** [comment]
- Version `^5` of this library will continue supporting DBAL `2.3+`/`3.0+` (and PHP `5.6+`)
- Version `^6` of this library now supports DBAL `4.0+` (and PHP `8.1+`)
